module Articulos where

articulos :: [[String]]
articulos =
  [ ["Dijkstra", "Scholten"]
  , ["Dijkstra", "Martin", "Lamport", "Scholten"]
  , ["Dijkstra", "Feijen"]
  , ["Feijen", "Boyer"]
  , ["Hunt", "Boyer"]
  , ["Hunt", "Ramanathan"]
  , ["Kaufmann", "Moore", "Boyer"]
  , ["Boyer", "Cortes"]
  , ["Cortes", "Fernandez"]
  , ["Fernandez", "Ramos"]
  , ["Ramos", "Diaz"]
  , ["Diaz", "Lopez"]
  , ["Lopez", "Garcia"]
  , ["Garcia", "Perez"]
  , ["Perez", "Rodriguez"]
  , ["Rodriguez", "Sanchez", "Martinez"]
  , ["Martinez", "Gomez", "Vargas"]
  , ["Vargas", "Ramirez"]
  , ["Ramirez", "Castro", "Rojas"]
  , ["Castro", "Jimenez"]
  , ["Jimenez", "Morales"]
  , ["Morales", "Pineda"]
  , ["Pineda", "Silva"]
  , ["Silva", "Torres", "Navarro"]
  , ["Navarro", "Clark", "Smith"]
  , ["Clark", "Johnson"]
  , ["Johnson", "Evans", "Baker"]
  , ["Evans", "Wilson"]
  , ["Wilson", "Taylor"]
  , ["Taylor", "Hernandez"]
  , ["Hernandez", "Ortega"]
  , ["Ortega", "Ruiz"]
  , ["Ruiz", "Dominguez"]
  , ["Dominguez", "Mendoza"]
  , ["Mendoza", "Vega"]
  , ["Vega", "Soto", "Muñoz"]
  , ["Muñoz", "Cabrera", "Flores"]
  , ["Flores", "Gutierrez", "Reyes"]
  , ["Reyes", "Salazar"]
  , ["Salazar", "Duran", "Castillo"]
  , ["Castillo", "Paredes", "Gonzalez"]
  , ["Gonzalez", "Maldonado"]
  , ["Maldonado", "Greco"]
  ]